tunnel: 2f84efc0-98d3-42b6-8ddf-c53d0bb0ce27
credentials-file: /home/patry/.cloudflared/2f84efc0-98d3-42b6-8ddf-c53d0bb0ce27.json

ingress:
  - hostname: reverb.hive.contractors
    service: http://127.0.0.1:8080
  - hostname: dev.hive.contractors
    service: http://127.0.0.1:8000
  - service: http_status:404
