<flux:select.option value="ALL">All Status</flux:select.option>
<flux:select.option value="Invited">Invited</flux:select.option>
<flux:select.option value="Estimate">Estimate</flux:select.option>
<flux:select.option value="Awaiting Response">Response</flux:select.option>
<flux:select.option value="Project Prep">Prep</flux:select.option>
<flux:select.option value="Scheduled">Scheduled</flux:select.option>
<flux:select.option value="Active">Active</flux:select.option>
<flux:select.option value="Complete">Complete</flux:select.option>
<flux:select.option value="Service Call">Service Call</flux:select.option>
<flux:select.option value="Service Call Complete">Service Call Complete</flux:select.option>
<flux:select.option value="Cancelled">Cancelled</flux:select.option>
<flux:select.option value="VIEW ONLY">VIEW ONLY</flux:select.option>
