<x-index-table.placeholder
    heading="Clients"
    :columns="\App\Livewire\Clients\ClientsTable::columnDefs()"
    :rows="\App\Livewire\Clients\ClientsTable::placeholderRows()"
    :compact="false"
    wire:transition
>
    <x-slot:actions>
        @include('livewire.clients.partials.table-actions')
    </x-slot:actions>
</x-index-table.placeholder>
